---
galaxy_info:
  author: sweetHome
  description: Terraform installation
  company: Sweet Home, Inc.
  license: Apache
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all

dependencies: []
