---
dependencies: []

galaxy_info:
  role_name: docker
  author: sweetHome
  description: Docker for Linux.
  company: Sweet Home, Inc.
  license: Apache
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - web
    - system
    - containers
    - docker
    - orchestration
    - compose
    - server
